#! /bin/sh

setxkbmap -layout us,en &

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0
bspc config top_padding		 30
bspc config focused_border_color #FFFFFF

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

