#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/Downloads/oneway.jpg &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           2
bspc config top_padding		 27
bspc config focused_border_color #FFFFFF

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

