#! /bin/sh


pgrep -x sxhkd > ~/.log/sxhkd || sxhkd &
polybar &
#$HOME/.config/polybar/launch.sh --hack &
#feh --bg-fill ~/Downloads/oneway.jpg &
#xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config click_to_focus true
bspc config focus_follows_pointer false
bspc config pointer_follows_focus false
bspc config border_width         1
bspc config window_gap           0
bspc config top_padding		 27
bspc config focused_border_color \#1e2127
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

