[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x282c33"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"

[font]
size = 16

[font.bold]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[keyboard]
bindings = [
  { key = "Return", mods = "Shift", chars = "\u001B[13;2u" },
  { key = "Return", mods = "Control", chars = "\u001B[13;5u" },

  { key = "V", mods = "Super", action = "Paste" },
  { key = "C", mods = "Super", action = "Copy" },
  { key = "V", mods = "Control", action = "ReceiveChar" },

  # panes
  { key = "P", mods = "Alt", chars = "\u0001\u0070" },
  { key = "P", mods = "Alt|Shift", chars = "\u0001\u0050" },
  { key = "H", mods = "Alt", chars = "\u0001\u0008" },
  { key = "H", mods = "Alt|Alt", chars = "\u0001\u0068" },
  { key = "J", mods = "Alt", chars = "\u0001\u000a" },
  { key = "J", mods = "Alt|Alt", chars = "\u0001\u006a" },
  { key = "J", mods = "Alt|Shift", chars = "\u0001\u004a" },
  { key = "K", mods = "Alt", chars = "\u0001\u000b" },
  { key = "K", mods = "Alt|Alt", chars = "\u0001\u006b" },
  { key = "K", mods = "Alt|Shift", chars = "\u0001\u004b" },
  { key = "L", mods = "Alt", chars = "\u0001\u000c" },
  { key = "L", mods = "Alt|Alt", chars = "\u0001\u006c" },

  # windows
  { key = "T", mods = "Alt", chars = "\u0001\u0014" },
  { key = "1", mods = "Alt", chars = "\u0001\u0031" },
  { key = "2", mods = "Alt", chars = "\u0001\u0032" },
  { key = "3", mods = "Alt", chars = "\u0001\u0033" },
  { key = "4", mods = "Alt", chars = "\u0001\u0034" },
  { key = "5", mods = "Alt", chars = "\u0001\u0035" },
  { key = "6", mods = "Alt", chars = "\u0001\u0036" },
  { key = "7", mods = "Alt", chars = "\u0001\u0037" },
  { key = "8", mods = "Alt", chars = "\u0001\u0038" },
  { key = "9", mods = "Alt", chars = "\u0001\u0039" },
  { key = "A", mods = "Alt", chars = "\u0001\u0001" },

  # break pane into new window
  { key = "T", mods = "Alt|Shift", chars = "\u0001\u0074" },

  # sessions
  { key = "S", mods = "Alt", chars = "\u0001\u0073" },
  { key = "E", mods = "Alt", chars = "\u0001\u0065" },

  { key = "U", mods = "Alt", chars = "\u0001\u0075" },
]


[scrolling]
history = 100000

[window]
decorations = "None"
opacity = 0.9
startup_mode = "Maximized"
dynamic_padding = true
option_as_alt = "Both"
blur = true

[terminal]

# macos
# [window.padding]
# x = 93

[terminal.shell]
program = "/sbin/tmux"
args = ["new-session", "-s", "DEFAULT", "-A"]
