[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xffffff"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "0xc678dd"
red = "0xe06c75"
white = "0xabb2bf"
yellow = "0xd19a66"

[colors.primary]
background = "0x282c33"
foreground = "0xabb2bf"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[keyboard]
bindings = [
#   { key = "Return", mods = "Shift", chars = "\u001B[13;2u" },
#   { key = "Return", mods = "Control", chars = "\u001B[13;5u" },
#
  { key = "V", mods = "Super", action = "Paste" },
  { key = "C", mods = "Super", action = "Copy" },
#   { key = "V", mods = "Control", action = "ReceiveChar" },
  { key = "1", mods = "Super", chars = "\u001B1" },
  { key = "2", mods = "Super", chars = "\u001B2" },
  { key = "3", mods = "Super", chars = "\u001B3" },
  { key = "4", mods = "Super", chars = "\u001B4" },
  { key = "5", mods = "Super", chars = "\u001B5" },
]


[scrolling]
history = 100000

[window]
decorations = "None"
opacity = 0.98
startup_mode = "Maximized"
dynamic_padding = true
option_as_alt = "Both"
blur = true

[terminal]
[terminal.shell]
program = "/sbin/tmux"
args = ["new-session", "-s", "👻", "-A"]
